name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write         # create release & upload assets
  pages: write            # deploy pages
  id-token: write         # needed for provenance
  attestations: write     # needed for provenance

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - uses: actions/configure-pages@v5

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build
        run: |
          bun build-dist
          test -f dist/index.html

      - name: Embed version and copy release asset
        run: |
          ver="${GITHUB_REF_NAME}"
          printf '\n<!-- version: %s commit: %s -->\n' "$ver" "$GITHUB_SHA" >> dist/index.html
          cp dist/index.html dist/iaslate.html
          test -f dist/iaslate.html

      - name: Generate checksum
        run: |
          cd dist
          sha256sum iaslate.html | tee iaslate.sha256

      - name: Upload job artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-dist
          path: dist
          if-no-files-found: error

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: site-dist
          path: dist

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
          generate_release_notes: true
          files: |
            dist/iaslate.html
            dist/iaslate.sha256

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: "dist/iaslate.html"

  deploy_pages:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
